package hr.fer.zemris.java.tecaj_13.web.servlets;

import java.io.IOException;

import javax.persistence.EntityManager;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import hr.fer.zemris.java.tecaj_13.dao.jpa.JPAEMProvider;
import hr.fer.zemris.java.tecaj_13.model.BlogUser;
import hr.fer.zemris.java.tecaj_13.web.forms.BlogUserForm;

/**
 * Servlet used to register new users.
 * 
 * @author staver
 *
 */
@WebServlet("/servleti/register")
public class RegisterServlet extends HttpServlet {

	private static final long serialVersionUID = 1L;

	/**
	 * Generates an empty user form and forwards it to appropriate jsp.
	 */
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

		BlogUser user = new BlogUser();
		BlogUserForm f = new BlogUserForm();
		f.fillFromUser(user);

		req.setAttribute("entry", f);
		req.getRequestDispatcher("/WEB-INF/pages/register.jsp").forward(req, resp);
	}

	/**
	 * Processes post requests generated by the registration form(BlogUserForm).
	 * Validates posted form and if everything is ok, creates new blog user and
	 * saves it to database(also creates it's session).
	 */
	@Override
	protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		req.setCharacterEncoding("UTF-8");

		String metoda = req.getParameter("metoda");
		if (!"Store".equals(metoda)) {
			resp.sendRedirect(req.getServletContext().getContextPath() + "/servleti/main");
			return;
		}

		BlogUserForm f = new BlogUserForm();
		f.fillFromHttpRequest(req);
		f.validateRegistration();

		if (f.hasErrors()) {
			req.setAttribute("entry", f);
			req.getRequestDispatcher("/WEB-INF/pages/register.jsp").forward(req, resp);
			return;
		}

		// Store to database
		EntityManager em = JPAEMProvider.getEntityManager();

		BlogUser user = new BlogUser();
		f.fillBlogUser(user);

		em.persist(user);

		// successful registration, set session attributes
		req.getSession().setAttribute("current.user.id", user.getId());
		req.getSession().setAttribute("current.user.fn", user.getFirstName());
		req.getSession().setAttribute("current.user.ln", user.getLastName());
		req.getSession().setAttribute("current.user.nick", user.getNick());

		resp.sendRedirect(req.getServletContext().getContextPath() + "/servleti/main");
	}

}
