package demo;

import hr.fer.zemris.lsystems.gui.LSystemViewer;

import hr.fer.zemris.lsystems.impl.LSystemBuilderImpl;
import hr.fer.zemris.lsystems.LSystem;
import hr.fer.zemris.lsystems.LSystemBuilderProvider;

/**
 * Class that draws a Koch curve configured by an array of strings.
 * 
 * @author Mauro Staver
 *
 */
public class Glavni2 {
	
	/**
	 * Main method that gets called when the program starts. It opens a GUI and
	 * generates an LSystem configured to draw a Koch curve and then draws it.
	 * 
	 * @param args command line arguments - not used here.
	 */
	public static void main(String[] args) {
		LSystemViewer.showLSystem(createKochCurve2(LSystemBuilderImpl::new));
	}
	
	/**
	 * The method returns an LSystem configured to draw a Koch curve.
	 * 
	 * @param provider LSystemBuilder object used for configuring the LSystem
	 * @return LSystem configured and generated by the LSystemBuilder
	 */
	private static LSystem createKochCurve2(LSystemBuilderProvider provider) {
		String[] data = new String[] {
				"origin                 0.05 0.4",
				"angle                  0",			
				"unitLength             0.9",
				"unitLengthDegreeScaler 1.0 / 3.0",
				"",
				"command F draw 1",
				"command + rotate 60",
				"command - rotate -60",
				"",
				"axiom F",
				"",
				"production F F+F--F+F" 
		};
		
		return provider.createLSystemBuilder().configureFromText(data).build();
	}
}
