package hr.fer.zemris.java.servlets;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 * Servlet that generates and returns as response an excel file (.xlsx) with
 * band voting results. The voting results are passed as a session parameter
 * 'bands' but if that parameter is null the excel file is generated by reading
 * results from appropriate text files, so this servlet doesn't strictly depend
 * on any passed parameters. Make sure that session parameter 'bands' is set
 * to latest voting results, or leave it as null.
 * 
 * @author staver
 *
 */
public class GlasanjeXlsServlet extends HttpServlet {

	private static final long serialVersionUID = 1L;

	/**
	 * Retrieves list of bands from session parameter 'bands' or generates it from
	 * appropriate text files. This list is then used to create an excel file which
	 * is sent as response.
	 */
	@SuppressWarnings("unchecked")
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		try (HSSFWorkbook hwb = new HSSFWorkbook()) {
			String resultsFileName = req.getServletContext().getRealPath("/WEB-INF/glasanje-rezultati.txt");
			String bandsFileName = req.getServletContext().getRealPath("/WEB-INF/glasanje-definicija.txt");

			List<Band> bands;

			if (req.getSession().getAttribute("bands") != null
					&& req.getSession().getAttribute("bands") instanceof List) {
				bands = (List<Band>) req.getSession().getAttribute("bands"); // assume list of bands
			} else {
				bands = Band.getResults(bandsFileName, resultsFileName);
			}

			HSSFSheet sheet = hwb.createSheet("Sheet 1");
			HSSFRow rowhead = sheet.createRow((short) 0);
			rowhead.createCell((short) 0).setCellValue("Bend");
			rowhead.createCell((short) 1).setCellValue("Broj glasova");

			for (Integer i = 0; i < bands.size(); i++) {
				HSSFRow row = sheet.createRow(i + 1);
				row.createCell((short) 0).setCellValue(bands.get(i).getName());
				row.createCell((short) 1).setCellValue(bands.get(i).getVotes());
			}

			resp.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
			resp.setHeader("Content-Disposition", "attachment; filename=\"rezultati.xlsx\"");
			hwb.write(resp.getOutputStream());

		} catch (Exception ex) {
			System.out.println(ex);
		}
	}

}
