package hr.fer.zemris.java.servlets;

import java.awt.BasicStroke;
import java.awt.Color;
import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtils;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 * Servlet that generates and returns as response a pie-chart(png image) showing
 * band voting results. The voting results are passed as a session parameter
 * 'bands' but if that parameter is null the pie-chart is generated by reading
 * results from appropriate text files, so this servlet doesn't strictly depend
 * on any passed parameters. Make sure that session parameter 'bands' is set to
 * latest voting results, or leave it as null.
 * 
 * @author staver
 *
 */
public class GlasanjeGrafikaServlet extends HttpServlet {

	private static final long serialVersionUID = 1L;

	/**
	 * Retrieves list of bands from session parameter 'bands' or generates it from
	 * appropriate text files. This list is then used to create a pie-chart which is
	 * sent in response as a png image.
	 */
	@SuppressWarnings("unchecked")
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		resp.setContentType("image/png");
		String resultsFileName = req.getServletContext().getRealPath("/WEB-INF/glasanje-rezultati.txt");
		String bandsFileName = req.getServletContext().getRealPath("/WEB-INF/glasanje-definicija.txt");

		try {
			List<Band> bands;

			if (req.getSession().getAttribute("bands") != null
					&& req.getSession().getAttribute("bands") instanceof List) {
				bands = (List<Band>) req.getSession().getAttribute("bands"); // assume list of bands
			} else {
				bands = Band.getResults(bandsFileName, resultsFileName);
			}

			JFreeChart chart = getChart(bands);
			int width = 500;
			int height = 350;
			ChartUtils.writeChartAsPNG(resp.getOutputStream(), chart, width, height);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * Generates and returns a pie-chart with voting results.
	 * 
	 * @param bands list of bands
	 * @return pie-chart with voting results.
	 */
	public JFreeChart getChart(List<Band> bands) {
		DefaultPieDataset dataset = new DefaultPieDataset();

		for (Band band : bands) {
			if (band.getVotes() != 0) {
				dataset.setValue(band.getName(), band.getVotes());
			}
		}

		boolean legend = true;
		boolean tooltips = true;
		boolean urls = false;

		JFreeChart chart = ChartFactory.createPieChart("Rezultati", dataset, legend, tooltips, urls);

		chart.setBorderPaint(Color.BLACK);
		chart.setBorderStroke(new BasicStroke(5.0f));
		chart.setBorderVisible(true);

		return chart;
	}

}
